targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/models/schemas/{{}}.dart': 'lib/src/models/schemas/generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/src/models/schemas/{{}}.dart': 'lib/src/models/schemas/generated/{{}}.freezed.dart'
